### PR TITLE
Put version info inside dropdown

### PR DESCRIPTION
**Pull request by jordanrogers-iop**
Hey @mfairchild365. Hopefully this make things a bit more tidy.

### CODE REVIEW

**Comment by mfairchild365** [comment]
First glance is that this looks good! I want to mull it over a bit more before I merge it though.

**Comment by jordanrogers-iop** [comment]
Hey @mfairchild365. Coming back to this I see some potential to structure the JSON better as to simplify displaying the data in the HTML. Will push my changes tomorrow.

**Comment by jordanrogers-iop** [comment]
Hey @mfairchild365. Finished doing some tidying up in the code. Please have a look when you are available.

**Comment by mfairchild365** [comment]
Thanks @jordanrogers-iop! I might not get to this until early next week.

**Comment by mfairchild365** [comment]
Sorry for the wait. I finally got a chance to look at this. Been dealing with a family emergency.

I think this is a fantastic step in the right direction. I tried to take a step back at look at this from the perspective of someone trying to answer the question "how old are these results?"

It occurred to me that there are two ways to answer that question.

1. Dates of the test results
2. Versions of what we tested against

We already have date information on the landing page, in the form of "Supported by x tests. Results range from y months ago to z years ago."

So I think the version information fits naturally with that.

How do you feel about making the following change?

1. Combine both SR and VC version sections and place it after the line of text about age of test results.
2. Then, also link the headings for test names to the tests.

**Comment by mfairchild365** [comment]
@jordanrogers-iop I'll probably have a bit of spare time before the end of the week. Do you want to work on this a bit more, or should I merge and make a few changes myself?

**Comment by jordanrogers-iop** [comment]
Hey @mfairchild365. Im going to struggle to get time to revisit this over the next few days so please feel free to go ahead and make the suggested edits. They sound like a great idea to help improve the UI and readability fo the version info.

**Comment by mfairchild365** [comment]
Sounds good. Thanks @jordanrogers-iop!

**Pull request merged**
