### PR TITLE
Update build script to work on Windows

### PR DESCRIPTION
**Pull request by RavenAlly**
I wasn't able to build the project in VS Code on Windows due to backslashes in file paths so updated the build script to adjust.

### CODE REVIEW

**Comment by mfairchild365** [comment]
@RavenAlly thank you for this! I tested it out and it works well!

I noticed that the title for the PR is for the build script, but there is also a change included for some test results. Did you mean to include those test result changes? If yes, in the future, I'd suggest submitting a separate PR for those. Just keeps things a bit more clean.

**Comment by RavenAlly** [comment]
Hi @mfairchild365 , sorry for the double submission, seems I still have a bit to learn about branching. 😳

**Comment by mfairchild365** [comment]
No worries. I'll merge for now :)

**Comment by Romeopuk** [comment]
Very gopd

**Pull request merged**
